apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: '${parameters.name}'
  name: '${parameters.name}-deployment'
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '${parameters.name}'
  template:
    metadata:
      labels:
        app: '${parameters.name}'
    spec:
      containers:
        - args:
            - '--spring.profiles.active=${parameters.springProfilesActive}'
          image: ${parameters.imageHost}/luversof/${parameters.artifactId}:${parameters.buildVersion}.${parameters.buildNumber}
          name: spring
          ports:
            - containerPort: ${#toInt(parameters.port)}
#          workingDir: /usr/local/app
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: ${#toInt(parameters.port)}
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: ${#toInt(parameters.port)}
            initialDelaySeconds: 20
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '${parameters.name}'
    spring-boot: "true"
  name: '${parameters.name}-service'
  namespace: default
spec:
  ports:
    - nodePort: ${#toInt(parameters.nodePort)}
      port: ${#toInt(parameters.port)}
      protocol: TCP
      targetPort: ${#toInt(parameters.port)}
  selector:
    app: '${parameters.name}'
  type: NodePort
