apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: '${name}'
  name: '${name}-deployment'
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '${name}'
  template:
    metadata:
      labels:
        app: '${name}'
    spec:
      containers:
        - args:
            - '--spring.profiles.active=${springProfilesActive}'
            - '--spring.application.name=${name}'
          workingDir: /usr/local/app
          image: '${imageHost}/luversof/${artifactId}:${buildVersion}.${buildNumber}'
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: '${port}'
            initialDelaySeconds: 20
            periodSeconds: 10
          name: spring
          ports:
            - containerPort: '${port}'
          resources:
            requests:
              cpu: '${requestsCpu}'
            limits:
              cpu: '${limitsCpu}'
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: '${port}'
            initialDelaySeconds: 20
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '${name}'
    spring-boot: 'true'
  name: '${name}-service'
  namespace: default
spec:
  ports:
    - nodePort: '${nodePort}'
      port: '${port}'
      protocol: TCP
      targetPort: '${port}'
  selector:
    app: '${name}'
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: '${name}'
  name: '${name}-hpa'
  namespace: default
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment
    name: '${name}-deployment'
  minReplicas: ${minReplicas} 
  maxReplicas: ${maxReplicas} 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
